### ISSUE TITLE
Profile Images can be mismatched

### ISSUE THREAD

**Issue by StevenBonePgh** [mike-ward/tweetz#88] opened 2021-08-21 12:24 UTC
After a long runtime  without restarting the application, I noticed that tweets can be rendered with an incorrect profile image. The profile images are from other users for which you have tweets from, and I have not detected a specific pattern to the mismatch. Having used Tweetz since the re-write I have not seen this before last week, where I noticed it twice (resolved via restart of the application).  

What changed? My computer now sleeps/wakes properly. Previously, the PC would crash on resume, which has finally been resolved, so I shutdown more frequently and/or disallowed sleep. This may be a red herring, or relevant to the underlying issue. 

I'd love to be able to have the opportunity to review the source and diagnose it myself, but figured I'd log the issue first and get to looking at it if/when I get some time. Thanks for an awesome and unobtrusive tweet viewer!

**Comment by mike-ward** [comment] 2021-08-21 14:40
First thing I would do is upgrade your device drivers. I've issues similar to this where users updated their graphics drivers and reported the problem resolved.

**Comment by mike-ward** [comment] 2021-08-21 17:04
Another thing to try is the latest beta build. It's essentially the same program compiled using .NET 6.0 Preview 7.

https://github.com/mike-ward/tweetz/suites/3559570428/artifacts/85405140

**Comment by mike-ward** [comment] 2021-09-21 23:44
Duplicate of #71

**Closed by mike-ward** 2021-09-21 23:44 UTC
Labels: duplicate
